#!/bin/bash

. /pkgscripts/include/pkg_util.sh

set +x
set +e

# SOURCE
SOURCEDIR="source"

# META
METADIR="/tmp/_pkg"
mkdir -p "${METADIR}"
mkdir -p "${METADIR}/conf"
mkdir -p "${METADIR}/scripts"

for f in INFO LICENSE PACKAGE_ICON*.PNG ; do
  if test -f "${f}" ; then
    cp "${f}" "${METADIR}"
  fi
done

for f in conf/PKG_DEPS ; do
  if test -f "${f}" ; then
    cp "${f}" "${METADIR}/conf"
  fi
done

for f in scripts/* ; do
  if test -f "${f}" ; then
    cp "${f}" "${METADIR}/scripts"
  fi
done


echo "METADATA"
echo "========"
find "${METADIR}"

# INSTALL STUFF
INSTDIR="/tmp/_install"

tar cvfJ package.txz synology-transcode
cp package.txz "${INSTDIR}"

echo "FILES"
echo "====="
tar tvfJ "${INSTDIR}/package.txz"


echo "INSTALLED"
echo "========="
find "${INSTDIR}"

# BUILD PACKAGE
pkg_make_package "${INSTDIR}" "${METADIR}"

mkdir -p /image/packages
pkg_make_spk "${METADIR}" /image/packages
