#!/bin/bash

. /pkgscripts/include/pkg_util.sh

set +x
set +e

# SOURCE
SOURCEDIR="source"

# META
METADIR="/tmp/_pkg"

for f in INFO LICENSE PACKAGE_ICON*.PNG conf/PKG_DEPS scripts/* ; do
  if test -f "${f}" ; then
    mkdir -p "${METADIR}/`dirname "${f}"`"
    cp "${f}" "${METADIR}/${f}"
  fi
done

for f in scripts/* ; do
  if test -f "${f}" ; then
    cp "${f}" "${METADIR}/${f}"
  fi
done


echo "METADATA"
echo "========"
find "${METADIR}"

# INSTALL STUFF
INSTDIR="/tmp/_install"

for f in usr/local/bin/synology-transcode ; do
  if test -f "${f}" ; then
    mkdir -p "${INSTDIR}/`dirname "${f}"`"
    cp "${f}" "${INSTDIR}/${f}"
  fi
done

echo "FILES"
echo "====="
find "${INSTDIR}"

# BUILD PACKAGE
pkg_make_package "${INSTDIR}" "${METADIR}"

mkdir -p /image/packages
pkg_make_spk "${METADIR}" /image/packages
