#!/bin/bash

. /pkgscripts/include/pkg_util.sh

# META
METADIR="/tmp/_pkg"
mkdir -p "${METADIR}"

for f in INFO LICENSE PACKAGE_ICON*.PNG ; do
  if test -f "${f}" ; then
    cp "${f}" "${METADIR}"
  fi
done

# INSTALL STUFF
INSTDIR="/tmp/_install"
mkdir -p "${INSTDIR}/usr/bin"

for f in synology-transcode ; do
  if test -f "${f}" ; then
    cp "${f}" "${INSTDIR}/usr/bin"
  fi
done

# BUILD PACKAGE
pkg_make_package /tmp/_install /tmp/_pkg
pkg_make_spk /tmp/_pkg /image/packages
