#!/bin/sh

#########################################
# A few variables to make things readable

# Package specific variables
PACKAGE="synology-transcode"
DNAME="Synology Transcode"

# Common variables
INSTALL_DIR="${SYNOPKG_PKGDEST}"
VAR_DIR="/usr/local/var/${PACKAGE}"
UPGRADE="/tmp/${PACKAGE}.upgrade"
PATH="${INSTALL_DIR}/sbin:/bin:/usr/bin:/usr/syno/bin" # Avoid ipkg commands

CTL_FILE=/usr/local/bin/transcode-ctl
BIN_FILE=/usr/local/bin/transcode

SYNOUSER="/usr/syno/sbin/synouser"

SYNO3APP="/usr/syno/synoman/webman/3rdparty"

#########################################
# DSM package manager functions

preinst ()
{
  # Need pip
  if which pip >/dev/null ; then
    true
  else
    # need to install pip
    wget https://bootstrap.pypa.io/get-pip.py && \
      python2 get-pip.py && \
      rm get-pip.py
  fi

  # Create $HOME - it might not exist, and supervisor installs
  # something there
  mkdir -p "$HOME"

  # Update pip. Why not?
  pip install -U pip

  # Install packages
  pip install watchdog supervisor

  exit 0
}

postinst ()
{
    # Installation directories
    mkdir -p ${INSTALL_DIR}
    mkdir -p ${VAR_DIR}
    mkdir -p /usr/local/bin

    # Remove the DSM user
    if ${SYNOUSER} --enum local | grep "^${PACKAGE}$" >/dev/null
    then
        # Keep the existing uid
        uid=`grep ${PACKAGE} /etc/passwd | cut -d: -f3`
        ${SYNOUSER} --del ${PACKAGE} 2> /dev/null
        UID_PARAM="-u ${uid}"
    fi

    ln -s /var/packages/${PACKAGE}/scripts/start-stop-status ${CTL_FILE}
    ln -s /var/packages/${PACKAGE}/target/usr/local/bin/transcode ${BIN_FILE}

    # Install the application in the main interface.
    if [ -d ${SYNO3APP} ]
    then
        rm -f ${SYNO3APP}/${PACKAGE}
        ln -s ${INSTALL_DIR}/share/synoman ${SYNO3APP}/${PACKAGE}
    fi

    # Create the service user if needed
    if grep "^${PACKAGE}:" /etc/passwd >/dev/null
    then
        true
    else
        adduser -h ${VAR_DIR} -g "${DNAME} User" -G users -D -H ${UID_PARAM} -s /bin/sh ${PACKAGE}
    fi

    # Correct the files ownership
    chown -Rh ${PACKAGE}:users ${INSTALL_DIR} ${VAR_DIR}

    exit 0
}

preuninst ()
{
    # Make sure the package is not running while we are removing it.
    ${CTL_FILE} stop

    exit 0
}

postuninst ()
{
    # Keep the user data and settings during the upgrade
    if [ -f ${UPGRADE} ]
    then
        true 
    else
        deluser ${PACKAGE}
        rm -fr ${VAR_DIR}
    fi

    # Remove the application from the main interface if it was previously added.
    if [ -h ${SYNO3APP}/${PACKAGE} ]
    then
        rm ${SYNO3APP}/${PACKAGE}
    fi

    # Remove symlinks to utils
    rm ${CTL_FILE}
    rm ${BIN_FILE}

    # Remove the installation directory
    rm -fr ${INSTALL_DIR}

    exit 0
}

preupgrade ()
{
    # The package manager only check the version when installing, not upgrading. So do it here the old way.
    if [ -e ${CTL_FILE} ]
    then
        touch ${UPGRADE}
    else
        false
    fi

    exit $?
}

postupgrade ()
{
    rm -f ${UPGRADE}

    exit 0
}
