#!/bin/sh

if test ! -z "$SYNOPKG_TEMP_LOGFILE" ; then
  `basename $0` > $SYNOPKG_TEMP_LOGFILE
fi

case "$1" in
  status)
    exit 3
    ;;
  start)
    ;;
  stop)
    ;;
  log)
    ;;
  *)
    ;;
esac
